### ISSUE TITLE
March 3rd 2020: `$` character unreadable in Jupyter notebooks rendering

### ISSUE THREAD

**Issue by TylerLeonhardt** [fastai/fastpages#172]
#### You must check both boxes

- [x] Have you searched opened / closed issues on this repo for a similar problem?
- [x] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

`$` dollar sign characters are hard to read.

Here's a sample notebook rendered: https://tylerleonhardt.github.io/fastpages-test/2020/03/03/Azure-PowerShell-VM-Visualization-Demo.html

![image](https://user-images.githubusercontent.com/2644648/75837571-181a6e00-5d7a-11ea-8253-e1f39f95c6e2.png)
![image](https://user-images.githubusercontent.com/2644648/75837584-1f417c00-5d7a-11ea-9908-8e080cee8652.png)

**Comment by hamelsmu** [comment]
@TylerLeonhardt the issue was resolved with https://github.com/fastai/fastpages/pull/174

To upgrade your repo, you can simply mimic the changes I made in that PR (only two lines).  Note that in the current version of fastpages there is a path for automated bug/fixees and upgrades but that is a version that is after the one you have in your repo 😢 

Please let us now if there is anything else we can help with!  Really look forward to your blog post!

**Comment by hamelsmu** [comment]
Edit: if you want the latest version of fastpages, which has a few other features, you can also use the template again, and copy your notebook(s) over.  I might recommend you do this so you have a version that easily upgradeable

**Comment by TylerLeonhardt** [comment]
> you can also use the template again

Does this mean make a new repo?

**Comment by hamelsmu** [comment]
Yeah make a new repo, perhaps rename the old one first so you can name your new repo with the same name.

After you do this, the upgrade process should be easier going forward
