### ISSUE TITLE
Where should I put the images which markdown file referenced

### ISSUE THREAD

**Issue by Herman-Wu** [fastai/fastpages#214]
As title, where should I put the images which markdown file referenced ?
If there are images in word, when it is been converted to md file, the system will put these images in "assets\img\[word file name]" folder and reference it through "{{ site.url }}{{ site.baseurl }}/assets/img". 
But if I manually do it (put and check in images at assets\img\[word file name] folder), it seems these images are not there. 
However if I put and check in images at  "imges/" folder, I can reference the images.  
Should I put all images the md file referenced in "images/" folder or I missed something?

**Comment by hamelsmu** [comment]
Yes if you manually want to place images somewhere, it is recommended to put them in `/images` and reference that directly.  

For the title, you can have to reference images in the `/images` folder.  This is because unlike other references, this is the one place where images do not get copied automatically for you.  

So you are correct.  Closing this issue feel free to ask other questions, but please also consider posting on forums.fast.ai if possible as you will have more visibility there.  thank you!

**Comment by Herman-Wu** [comment]
Thanks, yes, please close the issue and I will check forums.fast.ai  first next time. 
An update is actually put images in  assets\img\ folder also work. Since it's the folder that fastpages put imges when it converts word documents, I am considering also put my markdown files referenced images there so the folder structure can be consistent unless there are some side effects.
