### ISSUE TITLE
Deploying without ssh

### ISSUE THREAD

**Issue by chekos** [fastai/fastpages#22]
Hi! I know this template is in active development (I'm so excited for it!) but I already started using it this morning and I could not figure out how to set up the `ssh` keys. 
This is not a complaint - I'm sure it's easy to figure out if your not as impatient as I am lol

Anyways, I wanted to leave this issue so that others who may have problems too can do what I did if they so want to. 

This template is using `peaceiris/gh-pages` GitHub Action and perusing the [repo](https://github.com/peaceiris/actions-gh-pages) I noticed that you can use a personal token instead of `ssh` and it works just fine. 

I followed the instructions here https://github.com/peaceiris/actions-gh-pages/blob/master/README.md#%EF%B8%8F-personal_token

Thanks for the awesome tool! `fastpages` and `fast_template` are amazing!

**Comment by hamelsmu** [comment]
Did you try following the instructions on the README of this repo ?  

https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys

Did you set your deploy key to have `write` access?

**Comment by hamelsmu** [comment]
By the way you should not use a Personal Access Token, as that is not as secure as a SSH deploy key.  If someone gets a hold of your PAT they can access **all** of your repos.  an SSH deploy key is scoped only to one repo, so that is why these instructions are here.  

Closing this issue for now, feel free to make any more comments or ask any questions.  Please let us know how you are getting along and if you have any feedback

**Comment by peaceiris** [comment]
GitHub might have started to supporting to trigger the GitHub Pages build event by `GITHUB_TOKEN` on public repositories. (We can already use the token on private repositories.)

Be careful, there is no official announcement about this by GitHub.

```yaml
- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./_site
```

**Comment by hamelsmu** [comment]
Thanks @peaceiris I will check into this!  🙇
