### ISSUE TITLE
03-22-20: word document to blog post

### ISSUE THREAD

**Issue by rtmatx** [fastai/fastpages#228]
#### You must check both boxes

- [* ] Have you searched opened / closed issues on this repo for a similar problem?
- [*] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

1. I am trying to create an article from the word document and I am facing couple of issues. blog rendering is not working properly as I can't add layout tag for pandoc to convert the word document to post layout and 2) the picture that is in the word file is not available on the blog
2. [Link to blog post](https://mindrays.github.io/blogpost/2020/03/20/the-happiness-project-review-doc.html)
3. 
![image](https://user-images.githubusercontent.com/23462596/77501767-f7987d80-6e26-11ea-912e-9a8847bad39f.png)

Thanks
Ravi

**Comment by hamelsmu** [comment]
Can you please elaborate on 

> can't add layout tag for pandoc to convert the word document to post layout

What does that mean?

**Comment by rtmatx** [comment]
I looked more into issue of why a word document is not being able to be converted in to `post` layout like how a markdown document can be converted to `post` layout

The reason I found is that we can data metadata to markdown document (like `layout: post`) that can be used by `pandoc` while converting `markdown` to `html` or other formats. But I couldnt find a good way to add `layout` metadata to `word` document. 

Sorry if that sounds confusing. Let me know if you need more details to understand what I described. If so, I can add more details

**Comment by hamelsmu** [comment]
This is because you have alt text in your Word document.  This is not supported at the moment in fastpages for word docs.  Right click on your picture, and remove alt text and everything works.  

Word docs are the least feature-rich way to write blog posts in fastpages, and are meant for quick getting up and running.   There isn't a way you can specify any front matter or metadata for word documents in fastpages either.  You have to manually convert your document to markdown and then add the metadata yourself if you are interested in that.  

Sorry about this, perhaps if we get more time in the future we can build out support for Word.

**Comment by hamelsmu** [comment]
Actually no there is a bigger problem, so I'm reopening this issue - seems like there is no front matter being added at all ... something I will look into

**Comment by rtmatx** [comment]
Got it. I will remove `alt text` in the word document.
