### ISSUE TITLE
Latex not rendering despite setting use_math to true

### ISSUE THREAD

**Issue by ssundar6087** [fastai/fastpages#282]
## Required information

1. Steps to reproduce the problem
Set `use_math: true` in `_config.yml`, type out a latex equation in a jupyter notebook. While the notebook preview shows the correct formatting of the math equation, the same thing isn't reflected in the blog post where the code itself is displayed instead.

2. A link to the notebook or markdown file where the error is occurring
Link to the jupyter notebook (renders correctly) : https://github.com/ssundar6087/vision-and-words/blob/master/_notebooks/2020-05-01-DCGAN-CIFAR10.ipynb

Link to the blog post (does not render): https://ssundar6087.github.io/vision-and-words/python/computer%20vision/deep%20learning/gans/pytorch/2020/05/01/DCGAN-CIFAR10.html

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

Screenshot of config file:
![Screen Shot 2020-05-02 at 6 01 51 PM](https://user-images.githubusercontent.com/15097517/80896357-2f0a0d80-8ca2-11ea-9d53-b9d2ceba4309.png)

Screenshot of blog post where Latex hasn't rendered:
![Screen Shot 2020-05-02 at 6 01 33 PM](https://user-images.githubusercontent.com/15097517/80896363-34ffee80-8ca2-11ea-80d5-c5b67c5eac9d.png)

**Comment by prrao87** [comment]
Hi @hamelsmu, I was literally about to create the same issue - I thought I'd just piggyback off of this one instead. Just as mentioned by OP, I've enabled `use_math: true` in [my repo](https://github.com/prrao87/blog), and it's just not updating the MathJax equations from my notebook. 

![image](https://user-images.githubusercontent.com/35005448/80897535-86ae7600-8cae-11ea-9e2b-89a1b9a9fe01.png)

It's still displaying the text between the dollar signs as is. I double-checked that my version of fastpages is up-to-date and freshly auto-updated it earlier (version `2.1.25`, which is the same version as the current one on `fastpages` master). today. Is there a JavaScript file that's missing or something else that's different in my repo? I've been scratching my head on this one because clearly a lot of people before us have got this working.

**Comment by hamelsmu** [comment]
This was fixed by https://github.com/fastai/fastpages/pull/283

You must upgrade to get the fix.

**Comment by ssundar6087** [comment]
Thanks @hamelsmu . Upgrading fixed the issue 👍
