### ISSUE TITLE
Posts suddenly not sorted by date

### ISSUE THREAD

**Issue by caglorithm** [fastai/fastpages#287]
Hi!
Thanks for all the work! I'm was using sticky_rank to push one notebook to the top and usually the rest would be sorted by date. 

Curiously, after adding a new notebook today, suddenly the sorting changed: When I add stick_rank to a notebook, all the other posts are sorted by something else, I am guessing it is sorting by permalink, as far as I can see. 

Do you have any idea what could've gone wrong here? Or where do I start looking?

Thank you very much!

**Comment by hamelsmu** [comment]
Did not follow troubleshooting guide.

**Comment by caglorithm** [comment]
I did look at the guide and found [this page](https://forums.fast.ai/t/pinning-posts-aka-sticky-posts-in-fastpages/67923) that says that posts will be sorted by ascending sticky_post and then by descending date. It does not sort by date for me when I use sticky_rank.

**Comment by hamelsmu** [comment]
Did you follow the Troubleshooting guide?  Can you please post all of the requisite information in the issue

**Comment by hamelsmu** [comment]
It seems like you have not followed the troubleshooting guide, or at least have not read it carefully, because you have not provided the following information

![image](https://user-images.githubusercontent.com/1483922/81086464-64cf1200-8ead-11ea-99f2-5d6c490aeb7b.png)

Also it is clear you did not follow the steps outlined in the troubleshooting guide as you did not for example upgrade your repository.  

Please do your part to help by carefully following instructions and providing information that I can use to troubleshoot to make maintenance sustainable.  appreciate your help.

**Comment by caglorithm** [comment]
@hamelsmu I've updated fastpages and it's working again. Maybe something in your dockerfile has changed which made my old version imcompatible? Anyway, it's all as expected now and I'm very thankful for all your work!

Have a great day!
