### ISSUE TITLE
Please add instructions to use minima dark skin

### ISSUE THREAD

**Issue by TravisEz13** [fastai/fastpages#291]
**Is your feature request related to a problem? Please describe.**
Please add instructions to use minima dark skin

**Describe the solution you'd like**
Instruction on how to use it

**Describe alternatives you've considered**
I tried using it my self, but the structure described on minima's page doesn't match what fast pages looks like

**Additional context**

**Comment by hamelsmu** [comment]
I tried the dark skin, it wasn't compatible with other customizations in fastpages.  So sorry, not really a good path for this now.

**Comment by drscotthawley** [comment]
Might be nice to have a note in README telling people that, even though minima is the theme, minima's skins are NOT supported.  Because currently it says

> If you want to customize the styling or layout of fastpages, you can find instructions in minima's README...

Which is what I did, and then struggled for a while tonight wondering why my setting of minima's dark skin in `_config.yaml` was having no effect.  
Tried adding contents of minima's `skins/` directory and then selecting dark.  But it didn't make anything dark, all it did was grey out some of the text. 
...finally did a search and found this page. :-(
