### ISSUE TITLE
Option to add the date when an article is updated

### ISSUE THREAD

**Issue by rednafi** [fastai/fastpages#321]
Suppose I've written an article on **January 1, 2020** and updated it later on **January 1, 2021**. It'd be cool if we had the option to add the **latter date** along with the **publication date** automatically.

There can be another flag that will add the **last updated date** along with the **original publication date** to every article (if it exists).

Currently, I'm manually adding the **last updated date** to the top of the article (when applicable).

**Comment by hamelsmu** [comment]
I see you have to change the date on the article yourself.  Its going to be really complicated because then I will have to commit the markdown files to the repository and the dates will get out of sync.   Also if you change this date the sort order will change.  This request is too complicated with respect to the maintenance burden vs. benefit.  

Thanks for the idea and proposing it.
