### ISSUE TITLE
Failing after the fix upgrade

### ISSUE THREAD

**Issue by byteshiva** [fastai/fastpages#377]
Failing after the fix upgrade

Error :
```
cp: cannot stat '../current_files/_sass/minima/custom-variables.scss': No such file or directory
```
Details available at
https://github.com/byteshiva/blog/runs/936635711?check_suite_focus=true
https://github.com/byteshiva/blog/runs/936640928?check_suite_focus=true

_Originally posted by @byteshiva in https://github.com/fastai/fastpages/issues/373#issuecomment-667615653_

**Comment by hamelsmu** [comment]
Can you do me a favor and update this file in your repo manually and see if the upgrade works?

https://github.com/fastai/fastpages/blob/master/.github/workflows/upgrade.yaml

**Comment by hamelsmu** [comment]
@byteshiva  You have to copy the workflow file I linked to above manually to replace your upgrade.yaml file.   Since there was a bug in the `upgrade.yaml` itself, you cannot fix it through an automated upgrade.  Usually, we can fix bugs through an upgrade, however this is not possible in this case.  

 I have [tested that on the current version of fastpages this is no longer a bug](https://github.com/hamelsmu/upgrade_test/pull/3).

**Comment by byteshiva** [comment]
It worked. Thanks @hamelsmu
