### ISSUE TITLE
Support a Copy button for code cells

### ISSUE THREAD

**Issue by dclong** [fastai/fastpages#412]
**Is your feature request related to a problem? Please describe.**
I want to show a Copy button next (or on top of) code cells so that my blog readers can easily copy code from my blog posts.

**Describe the solution you'd like**
Add a Copy button to all code cells. When users click on it, the content of the code cell should be copied. jupyter-book has implemented this feature. 

**Describe alternatives you've considered**

**Additional context**

**Comment by hamelsmu** [comment]
Happy to take a PR if you would like to add it!

**Comment by dclong** [comment]
Why is this feature request closed?

**Comment by hamelsmu** [comment]
@dclong you have done nothing wrong!  I only keep issues open if they are bugs or if I plan on working on it.  Since I do not plan on working on this copy feature I closed it.... this doesn't mean that a contribution from someone is not welcome 

This is the only way I can manage a project is to make sure open issues are things that need my attention.  Thanks for understanding
