### ISSUE TITLE
Latex math alignment not working as expected

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [fastai/fastpages#439]
## Required information

1. Steps to reproduce the problem
Create a cell in a notebook with the following:

```
\begin{align}
a + b & = c
d &= e
\end{align}
```

2. A link to the notebook or markdown file where the error is occurring
4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

screenshot of render:

![Untitled](https://user-images.githubusercontent.com/25370730/96514436-91a89300-125b-11eb-8099-4191ebc4c04f.png)

**Comment by hamelsmu** [comment]
Did you first enable this feature per the instructions on the README?

**Comment by PaperPlaneSoftware** [comment]
Yes, sorry I forgot to mention that. All math wrapped in $$ works fine but not using /begin and /end.

I've also tried changing the math engine to mathjax and get the same error.

**Comment by hamelsmu** [comment]
yeah I think you need to use `$$` the other stuff doesn't work. Is there a reason that `$$` is not acceptable?

**Comment by PaperPlaneSoftware** [comment]
Ok, I don't think you can align equations using `$$`

**Comment by yusuf01019** [comment]
Yozz86

**Comment by hamelsmu** [comment]
@PaperPlaneSoftware perhaps see this example using LaTex from @drscotthawley https://drscotthawley.github.io/blog/2019/12/21/PCA-From-Scratch.html

**Comment by drscotthawley** [comment]
Hey, thanks for the mention, but I don't think I've tried using align environments yet.  From what I can gather from the [many StackExchange posts](https://www.google.com/search?q=equation+alignment+in+mathjax&oq=equation+alignment+in+mathjax+&aqs=chrome..69i57j0.7699j1j1&sourceid=chrome&ie=UTF-8) about equation alignment in MathJax, it seems like OP was doing it "correctly" but somehow (my gueess) nbdev was reformatting this code before MathJax could "see" it.  

So this may still be an open issue.  

I recall that Sylvain Gugger added a Liquid code that could function like a "verbatim" environment to nbdev so that users could get around such reformatting problems; so perhaps look into that; it's been a while since I tried so I don't remember it exactly.

**Comment by austin-hoover** [comment]
It would be very nice to use the align environment.

**Comment by eduardbermejo** [comment]
Any updates regarding this issue?

**Comment by agupta83** [comment]
This renders as expected

```
$$
\begin{aligned}
a + b &= c \\
d &= e
\end{aligned}
$$
```

**Comment by austin-hoover** [comment]
That seems to work. The only thing you can't do is label each aligned equation. For example, this doesn't work:

$$
\begin{aligned}
    a + b &= c \tag{1} \\
    d &= e \tag{2}
\end{aligned}
$$

This works in Jupyter but doesn't show up on the blog:

\begin{align}
    a + b &= c \tag{1} \\
    d &= e \tag{2}
\end{align}
