### ISSUE TITLE
Optimize Page Load Speed

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#46]
https://blog.webjeda.com/jekyll-speed/

**Comment by hamelsmu** [comment]
Not doing this.

**Comment by stefanbschneider** [comment]
@hamelsmu I'm running [my blog](https://stefanbschneider.github.io/blog/) with fastpages and I really like it. Unfortunately, Google Search Console tells me that there are performance issues with my page, which likely also leads to worse ranking on Google search.

So, I'm looking into ways for improving page speed and wanted to know your opinion. If they are useful, I can integrate these improvements into my blog and also open a PR for fastpages.

---

According to https://pagespeed.web.dev, a key issue are render-blocking resources, which lead to slow first contentful paint and time to interactive.

E.g., loading [`primer.css` in the custom head](https://github.com/fastai/fastpages/blob/master/_includes/custom-head.html#L10) blocks loading for almost 1s for me.
What is `primer.css` used for in fastpages? Is it just used for favicons? If `primer.css` is needed but not critical, could we load it asynchronously using `preload` [as suggested here](https://web.dev/render-blocking-resources/#how-to-eliminate-render-blocking-stylesheets)?

Are there any other simple optimizations that you could think of to improve page speed? 

For example, we could auto-generate webp images (e.g., with [jekyll-webp](https://github.com/sverrirs/jekyll-webp)) and load those if available, to speed up image loading.

Looking forward to your response.

**Comment by stefanbschneider** [comment]
One more idea: What about configuring and loading math-related resources per page, rather than in the head for all pages?
In my blog, I use math equations only in a small fraction of blog posts but the resources are still loaded in the custom head for all posts.

Is there are feature to disable math formatting by default, but overwrite the default and enable it for specific pages/posts in the frontmatter? And then to just load the corresponding resources for these pages?

I believe this should be quite easy to add. And we could keep the defaults as they currently are, so there are no changes for existing users.
