### ISSUE TITLE
Enable Pagination

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#48]
I haven't tested if pagination is working (when you have more than N posts and want `previous` and `next` butttons) . 

Here is an article that may help . https://blog.webjeda.com/jekyll-pagination/

**Comment by mikonapoli** [comment]
Had a read to the docs linked, and wanted to have a stab at this after I finished with #49  but I cannot find where the post list is built in the index page. In other words: `index.md` contains only a bit of content, but when the site is actually built a list of posts is added. I think I am looking for the "home" layout, but I cannot find it

**Comment by mikonapoli** [comment]
I have tried for a bit, but the answer is that apparently it is not possible, or not in an easy way. There are two main issues:

1) Although [this minima layout](https://github.com/jekyll/minima/blob/master/_layouts/home.html) has been pushed to master, for some reason it's not being picked up (we might be using a different theme or a different version, I don't know). This is not a major deal, and it can be solved with a custom layout, although it is a bit hacky

2) The paginator _requires_ the index to be `index.html` rather than `index.md` (I am guessing so that it can duplicate it several time depending on how many pages are needed. This does not seem easily solvable to me unless we are willing to break the basic assumptions of fastpage.

**Comment by hamelsmu** [comment]
Indeed looks like [pagination is built in to the currenty version of minima](https://github.com/jekyll/minima/blob/master/_layouts/home.html), however, they haven't cut a release yet so its not available for people installing via Gem.  

I'm not adventurous enough to copy their files etc.  Perhaps we look at the upcoming 3.0 release and see what has changed ( or actually wait until 3.1 )

**Comment by mikonapoli** [comment]
Perhaps. Should we label this issue as "waiting" or something?

**Comment by hamelsmu** [comment]
I’ll keep it open for a bit  :)

**Comment by zonca** [comment]
I made pagination working following https://github.com/jekyll/minima/pull/150#commitcomment-23340591

1) Added `gem 'jekyll-paginate'` to `Gemfile`

2) added to `_config.yml`:

```
gems:
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/
```

3) I had an empty `index.md` so just renamed it, I guess people with some content should turn it into html.

    mv index.md index.html

See at: https://zonca.dev/

**Comment by hamelsmu** [comment]
@zonca this is great!  Thanks for sharing!  I'll get around to this soon

**Comment by hamelsmu** [comment]
One issue with using the paginate plugin is that you have to convert index.md to index.html, and it becomes much harder to write content this way.  Any ideas on how to make things easier to let people write content on their home page?

**Comment by zonca** [comment]
@hamelsmu What if in the build action `fastpages`  adds a script which converts `index.md` to `index.html` before it is processed by Jekyll?

**Comment by hamelsmu** [comment]
No that wouldn't work in this case.  And there isn't a way to ship markdown inside HTML, either. the best way is to try to find a way to port pagination to markdown via {% includes %} or something like that or by extending _layout/home.html

**Comment by zonca** [comment]
what if you strip the front matter, do the conversion using `pandoc` or some other tool, and join back the front matter?

**Comment by hamelsmu** [comment]
@zonca don't want to hack it like that seems like it would not be very maintainable.

I'm thinking to just put a link to your instructions in the documentation instead?

**Comment by zonca** [comment]
Sure
