### ISSUE TITLE
Test if documentation is sufficient for getting started

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#49]
We need to go through the process of forking this repo and performing all the setup steps from scratch, and ensuring the documentation correctly reflects the proper setup process

**Comment by mikonapoli** [comment]
I went over the setup process and finally found to get the website up and running. Templated from a fork of the repo, so even if it is not important, it works from there too.

Issues I have found (depending on how you decide to go on I can raise a PR to address some of those).

1. in step 2 (modifying the badges) I knew what to do as I have done it before, but probably as a first timer I would have struggled understanding what part of the file is related to the badges

2. I had screwed up steps 3 and 4 as I had misunderstood the comments in the `_config.yaml` file:
```
# OPTIONAL: override baseurl and url if using a custom domain

# the subpath of your site, e.g. /blog

# you can comment the below line out if your repo name is not different than your baseurl
```
Namely I changed the subpath of my site to something different from the repo name in order to have a better looking url. This messed up the built website a lot. Even after changed it back, I had to push a change to the `index.md` file in order for the GH action to rebuild the links correctly.

3. In step 7 the key to be used as a secret must be the private key! This was not clear to me, as I assuemed it had to be the same as I was assuming I had to use the same as the deploy_key (although in retrospect I should have known better)

4. In step 8 I actually had to create the `gh-pages` branch before the option to use it for the pages was available

5. I was getting 
```
Your site is having problems building: The tag twitter on line 73 in _posts/2020-01-14-test-markdown-post.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.
```
When the site was being built for the first time. Removing the line from the post fixed it, but it might have been related to the problems I was having above. Will try it again later.

6. It would be probably beneficial to write somewhere that until the dot in the bar turns from yellow to green (the actions on the latest commit), the website is still being built.

For reference: this is my commit history [https://github.com/mikonapoli/testfromfork/commits/master](https://github.com/mikonapoli/testfromfork/commits/master)

**Comment by hamelsmu** [comment]
Some questions

> Even after changed it back, I had to push a change to the index.md file in order for the GH action to rebuild the links correctly.

This is odd.  After you changed your `_config.yaml` the site did not update correctly?  Did you wait for the update?  It takes ~ 5minutes or so at the moment.

> Your site is having problems building: The tag twitter on line 73 in _posts/2020-01-14-test-markdown-post.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

Were you getting this error locally or in GitHub Actions?

Please feel free to submit a PR clarifying #'s  2, 3, 4

I should probably take on clarifying #'s 1, 5 & 6.  

Checklist is below:

- [ ] how-to modify badges
- [ ] clarify `_config.yaml`
- [ ] clarify secret
- [ ] add step to create gh-pages branch
- [ ] Troubleshoot twitter plugin
- [ ]  Clarify Actions runtime / process

**Comment by mikonapoli** [comment]
> This is odd. After you changed your _config.yaml the site did not update correctly? Did you wait for the update? It takes ~ 5minutes or so at the moment.

Yes, I changed the _cofig.yaml and the links to the posts where still pointing at the incorrect old one. Pushing a change to the index.md fixed it (you can see my last commit in the history above).

> Were you getting this error locally or in GitHub Actions?
Neither. I was having this issue in the "GitHub pages" secition of the repo settings. Will work on this over the weekend

**Comment by hamelsmu** [comment]
@mikonapoli please let me know if you continue to get the twitter error.   Thank you look forward to the PR

**Comment by mikonapoli** [comment]
@hamelsmu I tried putting the back the offending line and now it is working no problem. It must have been something caused by my other issues (either the private key confusion or the config mess up)

**Comment by FReeshabh** [comment]
@hamelsmu I was also getting the Twitter error when I was using fastpages. I'll be looking forward to the fixes!

**Comment by joaogui1** [comment]
@hamelsmu I followed the documentation but I'm getting an error on the site build action
`ERROR: not found ACTIONS_DEPLOY_KEY, PERSONAL_TOKEN, or GITHUB_TOKEN
`

**Comment by hamelsmu** [comment]
@joaogui1 did you add an ACTIONS_DEPLOY_KEY to your secrets?

**Comment by hamelsmu** [comment]
@FReeshabh are you using the latest version of fastpages?  You shouldn’t be getting an error now

**Comment by joaogui1** [comment]
Had a typo on the secret name, sorry!

**Comment by joaogui1** [comment]
Just an extra note, I think it would be good to clarify what links appear on the header of the site (I believe every page with a title attribute appears there, right?)
![image](https://user-images.githubusercontent.com/13261989/74599769-c8297f00-50ca-11ea-8f76-3ea9aa31ba5a.png)

**Comment by FReeshabh** [comment]
@hamelsmu @joaogui1  I'm still getting the Twitter Tag Error. I'm also not being allowed to use the gh-pages to built the website

**Comment by hamelsmu** [comment]
@FReeshabh please provide a link to your repo.  Are you using fast_template or fastpages?

**Comment by joaogui1** [comment]
I'm having the same problems as @FReeshabh, but since I can use master to build the website, I'm just using that

**Comment by mikonapoli** [comment]
@FReeshabh and @joaogui1 if you add a `gh-pages` branch to your repo, you will be allowed to select the option. I will add a clarification to my PR

**Comment by joaogui1** [comment]
@mikonapoli I believe you can only use the gh-branch for the site if you're an organization
![image](https://user-images.githubusercontent.com/13261989/74604486-d941b280-5101-11ea-8a9d-ce5e9546ebf6.png)

**Comment by mikonapoli** [comment]
> @mikonapoli I believe you can only use the gh-branch for the site if you're an organization
> ![image](https://user-images.githubusercontent.com/13261989/74604486-d941b280-5101-11ea-8a9d-ce5e9546ebf6.png)

I am not an organisation. I admit that the message above is confusing, but on the other hand the [docs](https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites) state that

> The default publishing source for a project site is the `gh-pages` branch. If the repository for your project site has a `gh-pages` branch, your site will publish automatically from that branch.

**Comment by hamelsmu** [comment]
@joaogui1 

> I believe you can only use the gh-branch for the site if you're an organization

This is not true.  Individuals can create and use the gh-pages branch.  If it doesn't work initially try switching to master and switching back to gh-pages, you should see a message like this:

![image](https://user-images.githubusercontent.com/1483922/74607664-639cfe80-508f-11ea-8dd5-0ee416118c20.png)

**Comment by hamelsmu** [comment]
This issue has been closed by https://github.com/fastai/fastpages/pull/55

**Comment by joaogui1** [comment]
> @joaogui1
> 
> > I believe you can only use the gh-branch for the site if you're an organization
> 
> This is not true. Individuals can create and use the gh-pages branch. If it doesn't work initially try switching to master and switching back to gh-pages, you should see a message like this:
> 
> ![image](https://user-images.githubusercontent.com/1483922/74607664-639cfe80-508f-11ea-8dd5-0ee416118c20.png)
See this answer in Stack Overflow
https://stackoverflow.com/a/39978969/12038183

**Comment by hamelsmu** [comment]
@joaogui1 if you use the template and name your repo “blog” or anything other than your username.github.io you will be able to use the GH-pages branch
