### ISSUE TITLE
Is it possible to add Chinese search support?

### ISSUE THREAD

**Issue by invisprints** [fastai/fastpages#515]
**Is your feature request related to a problem? Please describe.**
I find the blog template using lunr.js for search function. It works well with English, but not for Chinese. I hope it could add Chinese search support.

**Describe alternatives you've considered**
I find [lunr-languages-zh](https://www.npmjs.com/package/lunr-languages-zh) is a new npm package that supports for Chinese search, and I wonder if we can add it for fastpages?

I'm not familiar with these, so I don't know if it's possible.

**Comment by hamelsmu** [comment]
I am not familiar with this, but would be happy to take a PR if someone can figure it out.

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
