### ISSUE TITLE
Text and image alignment when rendering notebooks

### ISSUE THREAD

**Issue by kushalj001** [fastai/fastpages#531]
**Is your feature request related to a problem? Please describe.**
I use jupyter notebooks to write my blogs. As such, I use a lot of equations and images along with text to convey my ideas. When  fastpages renders my blog I find that the text in my blog is left aligned. Similarly, if an image is too broad, it starts from the left but goes all the way to the right.  

**Describe the solution you'd like**
 I would like my large/broad images to be center-aligned when rendered. I would also like to know if there's a way to increase the width of my blog and align the text properly on the left as well as on the right side.

**Describe alternatives you've considered**
None
**Additional context**
The following images shows the issue. 
![image](https://user-images.githubusercontent.com/32245327/117536991-de975f80-b01b-11eb-80aa-2176ab5fc200.png)
The starting is well aligned on the left but the end at right is not uniform for all lines. Also, the image goes out of the text limit on the right.

**Comment by hamelsmu** [comment]
Can you share a link to your repo and blog post?

**Comment by kushalj001** [comment]
Blog link:
https://kushalj001.github.io/black-box-ml/language%20modeling/text-generation/vaes/posterior%20collapse/nlp/elbo/2021/05/05/Generating-Text-with-VAEs-and-Posterior-Collapse.html
Repo link:
https://github.com/kushalj001/black-box-ml

Thank you!

**Comment by saiamrit** [comment]
Hi @kushalj001 , For changing the blog width, you can refer to the following https://github.com/fastai/fastpages#adjusting-page-width
Hope that helps !

**Comment by kushalj001** [comment]
Thanks a lot, @saiamrit. Will try it out.

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
