### ISSUE TITLE
Floating table of contents option

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#533]
At the moment, it's possible to do 
```
toc: true
``` 
to autogenerate a table of contents. I think it would be nice if there were also styling options, e.g. to have that TOC float on one side of the page.

**Comment by hamelsmu** [comment]
I think this gets into customizing the theme, which I, unfortunately, don't have the bandwidth to do.   We hope to make a future version of fastpages with a couple of different themes that would allow for more customization.  

I like floating TOC too, was playing around with it in this [blog](https://python.hamel.dev/concurrency/)

**Comment by alexlenail** [comment]
I added a TOC to my blog. The diff is here: https://github.com/alexlenail/back_of_my_envelope/pull/19

Happy to close this issue.

**Comment by hamelsmu** [comment]
@alexlenail do you think there is a way to make this responsive so it looks good on mobile?  Happy to take a PR for this.  Thanks for your help

**Comment by anhhaibkhn** [comment]
Hi @alexlenail , and @hamelsmu 

Thank you for sharing your methods to customize the fastpage theme. I followed @alexlenail [diff's link](https://github.com/alexlenail/back_of_my_envelope/pull/19), and I could manage to make the table of contents floating, which is great. 
However, there are two problems that I am sure how to fix:
- The About Me section (in my _about.md_ ) text got misaligned on the browsers. 
- The python code snippets fonts became white background, which is more difficult to see (for me :D). 

Are there any ways to make the ToC floating, with minimum changes? 

Thank you for your help.

**Comment by anhhaibkhn** [comment]
Also, @hamelsmu  I wonder how you made this [blog](https://python.hamel.dev/concurrency/) ToC. it looks so nice and the code snippets font was easier to read, but I would like to stick with the current default dark theme for reading code. 

Thank you for your time. 
Best regards.

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
