### ISSUE TITLE
Numbered section headers

### ISSUE THREAD

**Issue by austin-hoover** [fastai/fastpages#536]
It might be nice to have the option to number the table of contents and section headers (1, 1.1, 1.1.1, etc.).

**Comment by hamelsmu** [comment]
You have to do this manually, but it can be done!  ex:

# 1 Top level

## 1.1 Child

**Comment by austin-hoover** [comment]
Haha, fair point.

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
