### ISSUE TITLE
Image path error when posting by word 

### ISSUE THREAD

**Issue by jun9** [fastai/fastpages#540]
### Image not shown when posting by uploading word document

In the HTML after pandoc conversion, the image url in the html is something like 
src="/assets/img/2021-05-20-Free-Revealing/media/image1.png" but it really should be like
src="../../../assets/img/2021-05-20-Free-Revealing/media/image1.png"

**Comment by hamelsmu** [comment]
I am not able to reproduce this error, and not enough information is given to troubleshoot or reproduce the error.    Images are rendering properly AFAIK, you may want to follow this repo's example carefully

https://github.com/fastai/fastpages/blob/master/_word/2020-01-01-Microsoft-Word-Example-Post.docx

also make sure your `_config.yaml` is filled out properly.  But I'm just guessing because of the vague error message with no code or anything to look at.  

Thanks.
