### ISSUE TITLE
First comment in a code cell is dropped

### ISSUE THREAD

**Issue by feras-oughali** [fastai/fastpages#574]
Hi, 

First comment in a code cell is dropped and is not visible in the rendered pages. 

Below is an example from fastpages:

code from original notebook.
```
# select a point for which to provide details-on-demand
label = alt.selection_single(
    encodings=['x'], # limit selection to x-axis value
    on='mouseover',  # select on mouseover events
    nearest=True,    # select data point nearest the cursor
    empty='none'     # empty selection includes no data points
)
```
Output in the corresponding page.
```
label = alt.selection_single(
    encodings=['x'], # limit selection to x-axis value
    on='mouseover',  # select on mouseover events
    nearest=True,    # select data point nearest the cursor
    empty='none'     # empty selection includes no data points
)
```
There is no issue with following comments. Only if the comment appears in the first line and it's not a directive.

**Comment by mcb00** [comment]
Try adding a leading blank line at the top of the code cell. See this [post](https://blog.mattbowers.dev/gradient-boosting-machine-with-any-loss-function) and its [notebook](https://github.com/mcb00/blog/blob/master/_notebooks/2021-10-23-gradient-boosting-machine-with-any-loss-function.ipynb) for examples.

**Comment by hamelsmu** [comment]
Yeah its a bit finicky sometimes.  @feras-oughali if you can link me to the original notebook I can try and take a look thanks.

**Comment by feras-oughali** [comment]
@hamelsmu Here is the link to the notebook: https://github.com/fastai/fastpages/blob/master/_notebooks/2020-02-21-introducing-fastpages.ipynb

Here is another example to overcome this issue: https://github.com/feras-oughali/blog/blob/master/_notebooks/2021-08-10-mixup.ipynb 
Here you would see leading blank comment at each code cell with comments. Removing that would remove the actual comment below that. 
@mcb00 thanks for the tip. Somehow, I figured this out. Just wanted to bring attention to the issue. 
Thanks,

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
