### ISSUE TITLE
Math is not properly rendered with Katex

### ISSUE THREAD

**Issue by anarinsk** [fastai/fastpages#577]
## Required information

1. Steps to reproduce the problem

Today I realized that LaTeX math is not properly rendered with default `katex` option in `_config.yml`.

```md
$$
\begin{aligned}
R^*=\underset{RR^t=I,\det(R)=1}{\operatorname{argmin}}\sum_{i=1}^n|RX_i-Y_i\|^2_2.
\end{aligned}
$$]\
```

a. The math equation is not **italicized**. 
b. The size of font is **smaller** than the size in inline math with `$...$` 

2. A link to the notebook or markdown file where the error is occurring

Following is the detail description of the issue.
 
https://anarinsk.github.io/lostineconomics-v2-1/2021/08/31/Testing-Katex.html

**Comment by abdksyed** [comment]
+1
Same here, when using `Katex` the math is nicely centered, but no italics and small font, when using null, the italics and fonts are good, but the equations are not centered.

**Comment by riven314** [comment]
I got the same issue on math equation rendering with `$$ ... $$`.
May I know if the issue has been followed up at the moment?

**Comment by riven314** [comment]
finally found a (temporary) fix for this. What you need to do is to append this line into your `fastpages-styles.scss` (set the size you want below):
```
.katex-display {
  font-size: 20px;
}
```

credit to @junongch

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
