### ISSUE TITLE
Generate notebook based files in a specific folder

### ISSUE THREAD

**Issue by adithyabsk** [fastai/fastpages#618]
**Is your feature request related to a problem? Please describe.**

I'm trying to use linting tools such as [markdownlint](https://github.com/DavidAnson/markdownlint) on my projects and would like to be able to specifically ignore the markdown files generated by the Jupyter convert action. I would still like to be able to lint blog posts I write in markdown. Since they are all added to the `_posts` directory, I have to to manually add each file to an ignore rule.

**Describe the solution you'd like**

If it were possible to put the generated markdown files in a specified folder, I could simply ignore that folder.

**Describe alternatives you've considered**

My current work around approach.

**Comment by adithyabsk** [comment]
I was able to find a solution to this issue, I just modified the output location of the `nb2post.py`. @hamelsmu Would a PR be accepted?

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
