### ISSUE TITLE
Option to group blogs under folders - for a tree hierarchy instead of current flat structure

### ISSUE THREAD

**Issue by Moniseeta** [fastai/fastpages#626]
**Is your feature request related to a problem? Please describe.**
I am using fastpages for blogging - and would like to maintain related blogs/series under folders. The current flat structure does not allow categorization or grouping, thus making it a little difficult to navigate/maintain.

**Describe the solution you'd like**
Requesting an option to maintain folder structure under "_posts" so that any series of related blogs can be grouped

**Describe alternatives you've considered**
Some way to tag similar blogs and render them as collapsed group. Clicking on each section will expand to show the blogs under that tag

**Comment by LuisAVasquez** [comment]
The same would make sense for the `_notebooks` folder. 


![Screenshot from 2022-04-05 11-55-33](https://user-images.githubusercontent.com/40602011/161728947-06deb225-1df6-44b3-93d6-c3e77630d6dd.png)

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
