### ISSUE TITLE
Jupyter notebook isn't displaying the python comments 

### ISSUE THREAD

**Issue by AnuragAnalog** [fastai/fastpages#631]
### You must follow ALL the steps in the [troubleshooting guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/TROUBLESHOOTING.md).  Not doing so may result in automatic closure of the issue.
**Yes, I have followed all the required steps in the troubleshooting guide**

## Required information

1. **My Jupyter notebook is not displaying the python comments which are present at the start of the cell.**

2. **Steps to reproduce the problem**
Just upload a notebook with a python comment at the start of the cell.

3. **A link to the notebook or markdown file where the error is occurring**
[https://anuraganalog.github.io/blog/kaggle/fbprophet/jupyter/tps/2022/03/24/Tabular-Playground-Series-Mar-2022-FB-Prophet.html](https://anuraganalog.github.io/blog/kaggle/fbprophet/jupyter/tps/2022/03/24/Tabular-Playground-Series-Mar-2022-FB-Prophet.html)

**Comment by AnuragAnalog** [comment]
Yeah, Its related to a bug.

**Comment by LottesofCode** [comment]
Was this bug solved?

**Comment by AnuragAnalog** [comment]
No

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
