### ISSUE TITLE
Difference between fast_template & fastpages

### ISSUE THREAD

**Issue by mrdbourke** [fastai/fastpages#93]
Hey team!

This looks amazing!

I was reading about fast_template yesterday and got the starter blog going.

Now I’ve seen this amazingness and I’m wondering what the difference is?

From what I’ve gathered so far, fastpages (here) incorporates nbdev natively?

A big thank you for all the hard wok.

**Comment by hamelsmu** [comment]
This issue will be closed by https://github.com/fastai/fastpages/pull/90

We will provide an official recommendation and explanation in a blog post soon, or feel free to read the PR if you want a preview!

**Comment by hamelsmu** [comment]
I'll actually answer it here - this is our recommendation

Because `fastpages` is more flexible and extensible, we recommend using it where possible. `fast_template` may be a better option for getting folks blogging who have no technical expertise at all, and will only be creating posts using Github's integrated online editor.
